<?php

namespace NewsBundle\Repository;

use NewsBundle\Entity\Post;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param integer $page
     * @return \Doctrine\ORM\Tools\Pagination\Paginator
     */
    public function findLatest($page = 1)
    {
        $query = $this->createQueryBuilder('Post')
            ->orderBy('Post.date', 'DESC')
            ->getQuery();

        $paginator = $this->paginate($query, $page);

        return $paginator;
    }

    /**
     * @param Doctrine\ORM\Query $dql   DQL Query Object
     * @param integer            $page  Current page (defaults to 1)
     * @param integer            $limit The total number per page (defaults to 5)
     *
     * @return \Doctrine\ORM\Tools\Pagination\Paginator
     */
    public function paginate($dql, $page = 1, $limit = 5)
    {
        $paginator = new Paginator($dql);

        $paginator->getQuery()
            ->setFirstResult(Post::POSTS_ON_PAGE * ($page - 1))
            ->setMaxResults(Post::POSTS_ON_PAGE);

        return $paginator;
    }
}
